config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'users/sessions' }
  namespace :api do 
    namespace :v1 do 
      resources :documentaries, param: :slug
      resources :books, param: :slug
      end
    end
 
    root to: 'homepage#index'
    get '/*path' => 'homepage#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer         not null, primary key
#  name       :string
#  content    :string
#  author     :string
#  sales      :decimal(, )
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  deleted_at :datetime
#  slug       :string
#  published  :string
#  price      :decimal(, )
#

class Book < ApplicationRecord
    has_many :documentaries, dependent: :destroy
    acts_as_paranoid

    before_create :book_paramaterize
    
    def book_paramaterize
        self.slug = name.parameterize 
    end
end

app/models/documentary.rb
class Documentary < ApplicationRecord
  belongs_to :book
  acts_as_paranoid
  before_create :documentary_paramaterize

  def documentary_paramaterize
    self.slug = documentary_name.parameterize 
  end
end

# == Schema Information
#
# Table name: documentaries
#
#  id                  :integer         not null, primary key
#  documentary_name    :string
#  book_name           :string
#  slug                :string
#  views               :decimal(, )
#  price               :decimal(, )
#  book_id             :integer         not null
#  created_at          :datetime        not null
#  updated_at          :datetime        not null
#  deleted_at          :datetime
#  documentary_content :string
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string          default(""), not null
#  encrypted_password     :string          default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_book, only: %i[show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    render json: @books
  end

  # GET /books/1 or /books/1.json
  def show
    render json: @book
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

      if @book.save
        render json: @book, status: :created
      else
        render json: @book.errors, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
      if @book.update(book_params)
       render json: @book
      else
       render json: { status: :unprocessable}
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find_by_slug(params[:slug])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :content, :author, :slug, :published, :price)
    end
end

app/controllers/api/v1/documentaries_controller.rb
module Api
  module V1
    class DocumentariesController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :set_documentary, only: %i[ show ]
      before_action :destroy_documentary, only: %i[ update edit destroy ]
      before_action :documentary_params, only: %i[ create update ]

      # GET /documentaries or /documentaries.json
      def index
        @documentaries = Documentary.all
        render :json => @documentaries
      end

      # GET /documentaries/1 or /documentaries/1.json
      def show
        render json: @documentary
      end

      # GET /documentaries/new
      def new
        @documentary = Documentary.new
      end

      # GET /documentaries/1/edit
      def edit
      end

      # POST /documentaries or /documentaries.json
      def create
        @documentary = Documentary.new(documentary_params)

          if @documentary.save
            render json: @documentary, status: :created
          else
            render json: @documentary.errors, status: :unprocessable_entity 
          end

      end

      # PATCH/PUT /documentaries/1 or /documentaries/1.json
      def update
        respond_to do |format|
          if @documentary.update(documentary_params)
            format.html { redirect_to documentary_url(@documentary), notice: "Documentary was successfully updated." }
            format.json { render :show, status: :ok, location: @documentary }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @documentary.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /documentaries/1 or /documentaries/1.json
      def destroy
        @documentary.destroy
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_documentary
           @documentary = Documentary.find_by_book_name(params[:slug])
        end

        def destroy_documentary
          @documentary = Documentary.find_by_slug(params[:slug])
       end

        # Only allow a list of trusted parameters through.
        def documentary_params
          params.require(:documentary).permit(:documentary_name, :book_name, :slug, :views, :price, :book_id, :documentary_name)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
    class Users::SessionsController < Devise::SessionsController
      skip_before_action :verify_authenticity_token
      before_action :configure_sign_in_params, only: [:create]
      before_action :destroy_user, only: [:destroy]

      # GET /resource/sign_in
      def new
        @user = User.all
        render :json => @user
      end

      # POST /resource/sign_in
      def create
        @user = User.new(configure_sign_in_params)

        if @user.save
          render :json => @user, status: :created
        else
          render :json => @user.errors, status: :unprocessable_entity 
        end
      end

      # DELETE /resource/sign_out
      def destroy
        @user.destroy
      end

      private

      def destroy_user
        @user = User.find_by_id(params[:id])
      end

      # If you have extra params to permit, append them to the sanitizer.
      def configure_sign_in_params
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/documentaries_helper.rb
module DocumentariesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.content %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @book.content %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/documentaries/_form.html.erb
<%= simple_form_for(@documentary) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :documentary_name %>
    <%= f.input :book_name %>
    <%= f.input :slug %>
    <%= f.input :views %>
    <%= f.input :price %>
    <%= f.association :books %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documentaries/edit.html.erb
<h1>Editing Documentary</h1>

<%= render 'form', documentary: @documentary %>

<%= link_to 'Show', @documentary %> |
<%= link_to 'Back', documentaries_path %>

app/views/documentaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documentaries</h1>

<table>
  <thead>
    <tr>
      <th>Documentary name</th>
      <th>Book name</th>
      <th>Slug</th>
      <th>Views</th>
      <th>Price</th>
      <th>Books</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documentaries.each do |documentary| %>
      <tr>
        <td><%= documentary.documentary_name %></td>
        <td><%= documentary.book_name %></td>
        <td><%= documentary.slug %></td>
        <td><%= documentary.views %></td>
        <td><%= documentary.price %></td>
        <td><%= documentary.books_id %></td>
        <td><%= link_to 'Show', documentary %></td>
        <td><%= link_to 'Edit', edit_documentary_path(documentary) %></td>
        <td><%= link_to 'Destroy', documentary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Documentary', new_documentary_path %>

app/views/documentaries/new.html.erb
<h1>New Documentary</h1>

<%= render 'form', documentary: @documentary %>

<%= link_to 'Back', documentaries_path %>

app/views/documentaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Documentary name:</strong>
  <%= @documentary.documentary_name %>
</p>

<p>
  <strong>Book name:</strong>
  <%= @documentary.book_name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @documentary.slug %>
</p>

<p>
  <strong>Views:</strong>
  <%= @documentary.views %>
</p>

<p>
  <strong>Price:</strong>
  <%= @documentary.price %>
</p>

<p>
  <strong>Books:</strong>
  <%= @documentary.books_id %>
</p>

<%= link_to 'Edit', edit_documentary_path(@documentary) %> |
<%= link_to 'Back', documentaries_path %>

app/views/homepage/index.html.erb
<%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
    <%= javascript_pack_tag "application" %> 
    <%= stylesheet_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= react_component("Homepage") %>